/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export const PlayerGL = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/player.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Paladin_J_Nordstrom" geometry={nodes.Paladin_J_Nordstrom.geometry} material={materials.Paladin_MAT} skeleton={nodes.Paladin_J_Nordstrom.skeleton} />
          <skinnedMesh name="Paladin_J_Nordstrom_Helmet" geometry={nodes.Paladin_J_Nordstrom_Helmet.geometry} material={materials.Paladin_MAT} skeleton={nodes.Paladin_J_Nordstrom_Helmet.skeleton} />
          <skinnedMesh name="Paladin_J_Nordstrom_Shield" geometry={nodes.Paladin_J_Nordstrom_Shield.geometry} material={materials.Paladin_MAT} skeleton={nodes.Paladin_J_Nordstrom_Shield.skeleton} />
          <skinnedMesh name="Paladin_J_Nordstrom_Sword" geometry={nodes.Paladin_J_Nordstrom_Sword.geometry} material={materials.Paladin_MAT} skeleton={nodes.Paladin_J_Nordstrom_Sword.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/player.glb')
